"""add threads

Revision ID: 7c15a13c8d5b
Revises: db0241027eaa
Create Date: 2025-05-30 11:22:10.478528

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c15a13c8d5b"
down_revision: Union[str, None] = "db0241027eaa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("initiator_id", sa.BigInteger(), nullable=True),
        sa.Column("initiator_username", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_threads_chat_id"), "threads", ["chat_id"], unique=False)
    op.add_column("messages", sa.Column("thread_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("messages_topic_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None,
        "messages",
        "threads",
        ["thread_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("messages", "topic_id")
    op.drop_column("messages", "sender_username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "sender_username",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "messages",
        sa.Column("topic_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_topic_id_fkey"),
        "messages",
        "topics",
        ["topic_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("messages", "thread_id")
    op.drop_index(op.f("ix_threads_chat_id"), table_name="threads")
    op.drop_table("threads")
    # ### end Alembic commands ###
