"""update last_name nullable

Revision ID: 8a57b1367995
Revises: 319d447460ed
Create Date: 2025-05-11 16:52:58.708716

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a57b1367995"
down_revision: Union[str, None] = "319d447460ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=128),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(length=128),
        nullable=False,
    )
    # ### end Alembic commands ###
