"""some refactor

Revision ID: cf1bb15de5ff
Revises: d69afc3071eb
Create Date: 2025-05-30 15:48:56.533035

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf1bb15de5ff"
down_revision: Union[str, None] = "d69afc3071eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("messages", "thread_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_column("messages", "confidence_score")
    op.add_column("threads", sa.Column("confidence_score", sa.Float(), nullable=False))
    op.alter_column(
        "threads",
        "initiator_id",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    op.alter_column(
        "threads",
        "initiator_username",
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
    )
    op.alter_column("threads", "topic_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("threads", "topic_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "threads",
        "initiator_username",
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
    )
    op.alter_column("threads", "initiator_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_column("threads", "confidence_score")
    op.add_column(
        "messages",
        sa.Column(
            "confidence_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column("messages", "thread_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
