"""remove chat_id from message

Revision ID: d69afc3071eb
Revises: 7c15a13c8d5b
Create Date: 2025-05-30 11:30:11.561001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69afc3071eb'
down_revision: Union[str, None] = '7c15a13c8d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_message_chat'), 'messages', type_='unique')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uix_message_chat'), 'messages', ['telegram_message_id', 'chat_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
