"""changed sender_id to sender_username

Revision ID: d933aa1a978b
Revises: 2e14e8281d77
Create Date: 2025-05-27 16:47:29.093732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd933aa1a978b'
down_revision: Union[str, None] = '2e14e8281d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_username', sa.String(length=32), nullable=True))
    op.drop_column('messages', 'sender_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_telegram_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_column('messages', 'sender_username')
    # ### end Alembic commands ###
