"""add session string

Revision ID: ff5a5845f8a7
Revises: 8a57b1367995
Create Date: 2025-05-13 17:52:52.393130

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff5a5845f8a7"
down_revision: Union[str, None] = "8a57b1367995"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_auth",
        sa.Column("session_string", sa.Text(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_auth", "session_string")
    # ### end Alembic commands ###
